import { NextRequest, NextResponse } from "next/server";

/**
 * LaTeX Export Route
 * Converts markdown manuscript content into a valid Elsevier-compatible .tex file
 */

function escapeLatex(text: string): string {
  return text
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/&/g, "\\&")
    .replace(/%/g, "\\%")
    .replace(/\$/g, "\\$")
    .replace(/#/g, "\\#")
    .replace(/_/g, "\\_")
    .replace(/\^/g, "\\textasciicircum{}")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\{/g, "\\{")
    .replace(/\}/g, "\\}");
}

function markdownTableToLatex(tableBlock: string): string {
  const lines = tableBlock.trim().split("\n").filter((l) => l.trim());
  if (lines.length < 2) return "";

  const header = lines[0]
    .split("|")
    .map((c) => c.trim())
    .filter(Boolean);
  const dataRows = lines.slice(2).filter((l) => !l.match(/^\|[-| :]+\|$/));

  const colCount = header.length;
  const colSpec = Array(colCount).fill("c").join(" | ");

  let tex = `\\begin{table}[htbp]\n\\centering\n\\caption{}\n\\label{tab:}\n\\begin{tabular}{| ${colSpec} |}\n\\hline\n`;
  tex += header.map((h) => `\\textbf{${escapeLatex(h)}}`).join(" & ") + " \\\\\\\\\n\\hline\n";

  for (const row of dataRows) {
    const cells = row
      .split("|")
      .map((c) => c.trim())
      .filter(Boolean);
    if (cells.length > 0) {
      // Pad or trim to match header count
      while (cells.length < colCount) cells.push("");
      tex += cells.slice(0, colCount).map((c) => escapeLatex(c)).join(" & ") + " \\\\\\\\\n\\hline\n";
    }
  }

  tex += `\\end{tabular}\n\\end{table}\n`;
  return tex;
}

function markdownToLatex(markdown: string, title: string, authors: string): string {
  const lines = markdown.split("\n");
  let body = "";
  let i = 0;
  let inTable = false;
  let tableBuffer: string[] = [];

  const flushTable = () => {
    if (tableBuffer.length > 0) {
      body += "\n" + markdownTableToLatex(tableBuffer.join("\n")) + "\n";
      tableBuffer = [];
      inTable = false;
    }
  };

  while (i < lines.length) {
    const line = lines[i];

    // Detect markdown table rows
    if (line.trim().startsWith("|")) {
      inTable = true;
      tableBuffer.push(line);
      i++;
      continue;
    } else if (inTable) {
      flushTable();
    }

    // Headings
    if (line.startsWith("# ")) {
      body += `\n\\section*{${escapeLatex(line.slice(2))}}\n`;
    } else if (line.startsWith("## ")) {
      body += `\n\\section{${escapeLatex(line.slice(3))}}\n`;
    } else if (line.startsWith("### ")) {
      body += `\n\\subsection{${escapeLatex(line.slice(4))}}\n`;
    } else if (line.startsWith("#### ")) {
      body += `\n\\subsubsection{${escapeLatex(line.slice(5))}}\n`;

    // Bullet lists
    } else if (line.trim().startsWith("- ") || line.trim().startsWith("* ")) {
      const prevLine = body.trimEnd();
      if (!prevLine.endsWith("\\begin{itemize}")) {
        body += "\\begin{itemize}\n";
      }
      body += `  \\item ${escapeLatex(line.trim().slice(2))}\n`;
      // Check if next line continues list
      if (i + 1 < lines.length && (lines[i + 1].trim().startsWith("- ") || lines[i + 1].trim().startsWith("* "))) {
        i++;
        continue;
      } else {
        body += "\\end{itemize}\n";
      }

    // Numbered lists
    } else if (line.trim().match(/^\d+\. /)) {
      const prevLine = body.trimEnd();
      if (!prevLine.endsWith("\\begin{enumerate}")) {
        body += "\\begin{enumerate}\n";
      }
      body += `  \\item ${escapeLatex(line.trim().replace(/^\d+\. /, ""))}\n`;
      if (i + 1 < lines.length && lines[i + 1].trim().match(/^\d+\. /)) {
        i++;
        continue;
      } else {
        body += "\\end{enumerate}\n";
      }

    // Bold + italic inline
    } else if (line.trim().length > 0) {
      let processed = escapeLatex(line);
      // Bold: **text**
      processed = processed.replace(/\\\*\\\*(.*?)\\\*\\\*/g, "\\textbf{$1}");
      // Italic: *text*
      processed = processed.replace(/\\\*(.*?)\\\*/g, "\\textit{$1}");
      // Inline code: `text`
      processed = processed.replace(/`(.*?)`/g, "\\texttt{$1}");
      body += processed + "\n\n";
    } else {
      body += "\n";
    }

    i++;
  }

  // Flush any remaining table
  flushTable();

  const template = `%% Elsevier LaTeX Template — Generated by Rankowise MCDM Platform
%% https://www.rankowise.online
\\documentclass[preprint,12pt]{elsarticle}

\\usepackage[utf8]{inputenc}
\\usepackage{amsmath}
\\usepackage{amssymb}
\\usepackage{booktabs}
\\usepackage{graphicx}
\\usepackage{hyperref}
\\usepackage{geometry}
\\usepackage{array}
\\usepackage{longtable}
\\usepackage{multirow}
\\usepackage{xcolor}
\\geometry{margin=1in}

\\journal{Expert Systems with Applications}

\\begin{document}

\\begin{frontmatter}

\\title{${escapeLatex(title)}}

\\author{${escapeLatex(authors || "Author Name")}}
\\address{University, Department, City, Country}
\\ead{email@university.edu}

\\begin{abstract}
% Abstract will appear here after manuscript generation
\\end{abstract}

\\begin{keyword}
MCDM \\sep Multi-Criteria Decision Making \\sep Sensitivity Analysis \\sep Weight Assessment
\\end{keyword}

\\end{frontmatter}

%% ========================================
%% MANUSCRIPT BODY
%% Generated by Rankowise AI Manuscript Engine
%% ========================================

${body}

%% ========================================
%% BIBLIOGRAPHY
%% ========================================
\\bibliographystyle{elsarticle-num}
\\bibliography{references}

\\end{document}
`;

  return template;
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { content, title, authors, sectionName } = body;

    if (!content || content.trim().length === 0) {
      return NextResponse.json({ error: "No content provided" }, { status: 400 });
    }

    const paperTitle = title || "Multi-Criteria Decision Making Analysis: A Comprehensive Study";
    const latexContent = markdownToLatex(content, paperTitle, authors || "");

    return NextResponse.json({
      latex: latexContent,
      filename: `rankowise_${(sectionName || "manuscript").replace(/\s+/g, "_").toLowerCase()}.tex`,
    });
  } catch (err: any) {
    console.error("LaTeX export error:", err);
    return NextResponse.json({ error: err.message || "LaTeX conversion failed" }, { status: 500 });
  }
}
