import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

// ─── Statistical Helpers ─────────────────────────────────────

function sentenceVariance(text: string): number {
    const sentences = text.split(/[.!?]/).filter(Boolean);
    if (sentences.length < 2) return 100; // not enough data → assume human
    const lengths = sentences.map(s => s.trim().split(/\s+/).length);
    const avg = lengths.reduce((a, b) => a + b, 0) / lengths.length;
    const variance = lengths.reduce((a, b) => a + (b - avg) ** 2, 0) / lengths.length;
    return variance;
}

function lexicalDiversity(text: string): number {
    const words = text.toLowerCase().split(/\s+/).filter(Boolean);
    if (words.length === 0) return 1;
    const unique = new Set(words);
    return unique.size / words.length;
}

function finalAIScore(llmScore: number, variance: number, diversity: number): number {
    let score = llmScore;
    if (variance < 20) score += 10;   // low variance = more AI-like
    if (diversity < 0.4) score += 10; // low diversity = more AI-like
    return Math.min(100, Math.round(score));
}

// ─── Core Detection Prompt ────────────────────────────────────

const AI_DETECTION_PROMPT = (text: string) => `
AI AUTHORSHIP ANALYSIS MODE

You are an expert forensic linguist and AI detection analyst.

TASK:
Evaluate the following academic text and estimate the probability that it was generated by AI.

ANALYSIS CRITERIA:

1. Linguistic Uniformity:
   - Are sentence structures repetitive or overly consistent?

2. Perplexity & Variation:
   - Does the text lack natural variation in tone and phrasing?
   - Does sentence length vary naturally (human "burstiness")?

3. Specificity:
   - Does the text contain concrete data, context, and constraints?
   - Or does it use vague generalizations?

4. Reasoning Depth:
   - Are explanations shallow or deeply analytical?
   - Does the author explain WHY results occur, not just WHAT they are?

5. Human Markers:
   - Presence of nuanced arguments, subtle inconsistencies, or subjective reasoning
   - Dataset-specific anchoring (e.g., "among the 8 alternatives evaluated...")
   - Mixed analytical connectors (however, whereas, consequently, critically)

6. AI Markers:
   - Generic academic phrases ("this study aims", "it is important to note", "overall")
   - Predictable transitions ("furthermore", "moreover", "in conclusion")
   - Overly smooth readability with uniform paragraph structure
   - Passive constructions ("it was found that", "it can be seen")

TEXT TO ANALYZE:
"""
${text.slice(0, 3000)}
"""

OUTPUT FORMAT (STRICT — RETURN EXACTLY THIS):
AI Likelihood: X%
Human Likelihood: Y%
Risk Level: Low

DO NOT explain. DO NOT add any extra sentences. ONLY return the three lines above.
Risk Level must be exactly one of: Low, Medium, High
`;

// ─── POST Handler ─────────────────────────────────────────────

export async function POST(req: NextRequest) {
    try {
        const { text, userApiKey } = await req.json();

        if (!text || text.trim().length < 50) {
            return NextResponse.json({ error: "Text too short to analyze." }, { status: 400 });
        }

        // Get API keys
        let apiKeys: string[] = [];
        if (userApiKey && userApiKey.trim().length > 0) {
            apiKeys = [userApiKey.trim()];
        } else {
            const keysString = process.env.GEMINI_API_KEY || "";
            apiKeys = keysString.split(",").map((k: string) => k.trim()).filter((k: string) => k.length > 0);
        }

        if (apiKeys.length === 0) {
            return NextResponse.json({ error: "No API key available." }, { status: 500 });
        }

        // Statistical analysis (runs client-side equivalent on server)
        const variance = sentenceVariance(text);
        const diversity = lexicalDiversity(text);

        // LLM-based detection
        const detectionPrompt = AI_DETECTION_PROMPT(text);
        let llmAiPercent = 50; // default fallback
        let rawOutput = "";

        let lastError = null;
        for (const key of apiKeys) {
            try {
                const genAI = new GoogleGenerativeAI(key);
                const model = genAI.getGenerativeModel({
                    model: "gemini-2.5-flash",
                    generationConfig: {
                        temperature: 0.1, // Very low temp for consistent detection output
                        topP: 0.9,
                        topK: 10,
                        maxOutputTokens: 100,
                    },
                });

                const result = await model.generateContent(detectionPrompt);
                const response = await result.response;
                rawOutput = response.text().trim();

                // Parse the structured output
                const aiMatch = rawOutput.match(/AI Likelihood:\s*(\d+)%/i);
                if (aiMatch) {
                    llmAiPercent = parseInt(aiMatch[1]);
                }
                break; // success
            } catch (error: any) {
                lastError = error;
                continue;
            }
        }

        if (!rawOutput && lastError) {
            return NextResponse.json(
                { error: "Detection failed: " + (lastError?.message || "Unknown error") },
                { status: 500 }
            );
        }

        // Fusion: LLM + statistical
        const finalScore = finalAIScore(llmAiPercent, variance, diversity);
        const humanScore = 100 - finalScore;
        const risk: "Low" | "Medium" | "High" =
            finalScore > 70 ? "High" : finalScore > 40 ? "Medium" : "Low";

        // Build detailed breakdown
        const breakdown = {
            llmScore: llmAiPercent,
            statisticalPenalty: finalScore - llmAiPercent,
            sentenceVariance: Math.round(variance * 10) / 10,
            lexicalDiversity: Math.round(diversity * 100) / 100,
            varianceFlag: variance < 20,
            diversityFlag: diversity < 0.4,
        };

        return NextResponse.json({
            aiPercent: finalScore,
            humanPercent: humanScore,
            risk,
            breakdown,
            rawLLMOutput: rawOutput,
        });

    } catch (error: any) {
        return NextResponse.json(
            { error: "Detection error: " + (error.message || "Unknown") },
            { status: 500 }
        );
    }
}
